Log prefix expression support
google/nftables pull request #146
Opened 2022-02-15 20:48 UTC by turekt

Hi,

I have added the `expr.Log` case to the `name` switch of the `unix.NFTA_DATA_EXPR` case as proposed in https://github.com/google/nftables/issues/115 which adds the support for log prefix parsing. I have also enriched your existing `GetRule` test to check the log prefix expression support and whether the addition works correctly.

Let me know what you think.

2022-02-17 17:18 UTC, stapelberg requested changes
Thanks for adding this!

I think it’d be slightly cleaner to not extend the existing TestGetRule, but rather add a new test specifically for log expressions, just like TestDynset.

2022-02-17 20:47 UTC, turekt commented
I have extracted the test for log expressions by writing a new test just like the `TestDynset`. I am sure that you are aware, but I want to note that this test has to run with the `-run_system_tests` flag to not be skipped:
```
$ sed -n 256,257p rule.go
					//case "log":
					//	e = &expr.Log{}
$ go test -run_system_tests -run "TestExprLogPrefix"
--- FAIL: TestExprLogPrefix (0.00s)
    nftables_test.go:623: unexpected number of exprs: got 0, want 1
FAIL
exit status 1
FAIL	github.com/google/nftables	0.003s
$ vim rule.go
$ sed -n 256,257p rule.go
					case "log":
						e = &expr.Log{}
$ go test -run_system_tests -run "TestExprLogPrefix"
PASS
ok  	github.com/google/nftables	0.003s
```

Let me know if this is ok.

2022-02-19 19:57 UTC, stapelberg approved these changes

2022-02-19 19:57 UTC, merged

2022-02-19 19:57 UTC, stapelberg commented
Thanks!