add set element expires field
google/nftables pull request #223
Opened 2023-04-19 01:50 UTC by iwind

add "expires" field to SetElement, and improve "Conn.GetSetElements()" to decode the "expires" field value when it's available.

2023-04-20 15:24 UTC, stapelberg approved these changes

2023-04-20 15:26 UTC, stapelberg requested changes

2023-04-21 01:49 UTC, iwind commented on set.go
> +				s.Expires = time.Millisecond * time.Duration(ad.Uint64())
No, it's a computed value by nftables.

2023-04-21 06:26 UTC, stapelberg approved these changes

2023-04-21 06:26 UTC, merged