feat: add monitor on table chain rule set setelem and obj events
google/nftables pull request #250
Opened 2023-12-07 15:02 UTC by singchia

- add monitor feature
- optimize multiple header types assertion(which needed by monitor)

2023-12-08 07:28 UTC, stapelberg requested changes
Thanks for your PR! Did a first review, but I probably have more comments once these are out of the way :)

2023-12-08 07:28 UTC, stapelberg commented on monitor.go
> +	monitor.mtx.Unlock()
Always call Unlock() via defer: 

```go
monitor.mu.Lock()
defer monitor.mu.Unlock()
```

2023-12-08 07:28 UTC, stapelberg commented on monitor.go
> +		conn.JoinGroup(uint32(unix.NFNLGRP_NFTRACE))
Why are we ignoring the error here?

2023-12-08 07:28 UTC, stapelberg commented on monitor.go
> +		err = conn.JoinGroup(uint32(unix.NFNLGRP_NFTABLES))
if err := conn.JoinGroup(uint32(unix.NFNLGRP_NFTABLES)); err != nil {

2023-12-08 07:42 UTC, singchia commented on monitor.go
> +func lazyInit() {
ok, learned

2023-12-08 08:09 UTC, singchia commented on monitor.go
> +	mtx     sync.Mutex
sure

2023-12-08 08:12 UTC, singchia commented on monitor.go
> +			if got, want := msg.Header.Type&0xff00>>8, netlink.HeaderType(unix.NFNL_SUBSYS_NFTABLES); got != want {
ok

2023-12-08 10:57 UTC, singchia commented on monitor.go
> +	monitor.mtx.Unlock()
ok fixed

2023-12-09 17:43 UTC, stapelberg requested changes

2023-12-09 17:43 UTC, stapelberg commented on monitor.go
> +	Data  interface{}
Oh, now I see why you couldn’t use `any` :) Yes, you can bump it to 1.18.

2023-12-09 17:43 UTC, stapelberg commented on monitor.go
> +			MonitorObjectTables:   1<<unix.NFT_MSG_NEWTABLE | 1<<unix.NFT_MSG_DELCHAIN,
This line says NEWTABLE and DELCHAIN. Shouldn’t it be NEWTABLE and DELTABLE?

Same in the copy in line 58.

2023-12-12 18:41 UTC, stapelberg reviewed
Looks good! When you resolve the remaining two comments, I think this is ready to be merged :)

2023-12-12 18:41 UTC, stapelberg commented on monitor.go
> +type Event struct {
Let’s rename this to MonitorEvent to make the name more descriptive.

2023-12-12 18:41 UTC, stapelberg commented on monitor.go
> +	EventTypeDELChain   EventType = unix.NFT_MSG_DELCHAIN
This one should be EventTypeDelChain (not uppercase DEL)

2023-12-13 07:22 UTC, stapelberg approved these changes

2023-12-13 07:23 UTC, merged